# Generated by Django 4.2 on 2023-04-21 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Carreras')),
                ('duration', models.IntegerField(verbose_name='Duracion')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='carrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.carrers'),
        ),
    ]
