# Generated by Django 4.2 on 2023-04-21 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_carrers_student_carrer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carrers',
            new_name='Carrer',
        ),
    ]
