# Generated by Django 4.2.1 on 2023-05-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Carrera')),
                ('duracion', models.IntegerField(choices=[(1, 'UNO'), (2, 'DOS'), (3, 'TRES')], verbose_name='Duracion')),
                ('created_at', models.DateTimeField(max_length=100, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(max_length=100, verbose_name='Updateado el')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['-created_at'],
            },
        ),
    ]
