# Generated by Django 4.2.1 on 2023-05-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updateado el'),
        ),
    ]
