# Generated by Django 4.2.1 on 2023-05-05 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0003_materia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia',
            options={'verbose_name': ('Materia',), 'verbose_name_plural': ('Materias',)},
        ),
    ]
