# Generated by Django 4.2.1 on 2023-05-05 00:41

import carreras.choices
from django.db import migrations, models
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0004_alter_materia_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['-created_at'], 'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AddField(
            model_name='materia',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Creado el'),
        ),
        migrations.AddField(
            model_name='materia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='duracion',
            field=enumchoicefield.fields.EnumChoiceField(default=carreras.choices.DuracionMateria['SEMESTRAL'], enum_class=carreras.choices.DuracionMateria, max_length=13, verbose_name='Duración'),
        ),
    ]
