# Generated by Django 4.2.1 on 2023-06-09 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0005_alter_materia_options_materia_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='carreras.carrera', verbose_name='Carrera'),
        ),
    ]
